<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNzXvLCz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNzXvLCz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNzXvLCz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNzXvLCz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNzXvLCz\App_KernelDevDebugContainer([
    'container.build_hash' => 'NzXvLCz',
    'container.build_id' => '66e9add4',
    'container.build_time' => 1686004980,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNzXvLCz');
